services:
  - type: web
    name: res-unoki
    runtime: docker
    rootDir: webapp
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SECRET_KEY
        generateValue: true
